url: http://improvglasgow.co.uk/
baseurl: 

# Site settings
title: Glasgow Improv Theatre - The GIT
email: glasgowimprovtheatre@gmail.com
description: "Glasgow Improv Theatre - The GIT. Improv classes, workshops, and shows in Glasgow, Scotland."

# Course links
101-link: https://www.facebook.com/events/164357222471723
101-date: 11th Sep 2021
201-link: https://goo.gl/forms/pz9jThIwVHwNrMBA2
201-date: 
301-link: https://www.facebook.com/events/900588193869636
301-date: 12th Sep 2021
401-link: https://goo.gl/forms/pz9jThIwVHwNrMBA2
401-date: 
fbevents-link: https://www.facebook.com/improvglasgow/events


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/improvglasgow
  - title: facebook
    url: http://facebook.com/improvglasgow
  - title: instagram
    url: http://instagram.com/improvglasgow
  - title: twitch
    url: http://twitch.tv/improvglasgow
  - title: youtube
    url: https://www.youtube.com/channel/UC7eUy-KQZLZS4rqLz_zQjnQ/

# Postal address (add as many lines as necessary)
address:
  - line: Blackfriars
  - line: 36 Bell St, Glasgow, Scotland, G1 1LG

# Build settings
markdown: kramdown
permalink: pretty
