url: http://improvglasgow.co.uk/
baseurl: 

# Site settings
title: Glasgow Improv Theatre
email: glasgowimprovtheatre@gmail.com
description: "Glasgow Improv Theatre - The GIT. The home of improv comedy in Glasgow, Scotland."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/improvglasgow
  - title: facebook
    url: http://facebook.com/improvglasgow

# Postal address (add as many lines as necessary)
address:
  - line: Blackfriars
  - line: 36 Bell St, Glasgow, Scotland, G1 1LG

# Build settings
markdown: kramdown
permalink: pretty
