url: http://improvglasgow.co.uk/
baseurl: 

# Site settings
title: Glasgow Improv Theatre - The GIT
email: glasgowimprovtheatre@gmail.com
description: "Glasgow Improv Theatre - The GIT. Improv classes, workshops, and shows in Glasgow, Scotland."

# Course links
101-link: 'https://fb.me/e/1sXVAdY2K'
101-date: 23rd Jan 2022 (SOLD OUT)
201-link: 'https://www.facebook.com/events/436100864896380'
201-date: 22nd Jan 2022 (SOLD OUT)
301-link: 'https://fb.me/e/25KHsUGlM'
301-date: 22nd Jan 2022
401-link: ''
401-date: 
fbevents-link: https://www.facebook.com/improvglasgow/events
mailing-list-link: https://goo.gl/forms/pz9jThIwVHwNrMBA2


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/improvglasgow
  - title: facebook
    url: http://facebook.com/improvglasgow
  - title: instagram
    url: http://instagram.com/improvglasgow
  - title: twitch
    url: http://twitch.tv/improvglasgow
  - title: youtube
    url: https://www.youtube.com/channel/UC7eUy-KQZLZS4rqLz_zQjnQ/

# Postal address (add as many lines as necessary)
address:
  - line: Blackfriars
  - line: 36 Bell St, Glasgow, Scotland, G1 1LG

# Build settings
markdown: kramdown
permalink: pretty
